name: sql injection test for users/userid/tasks post
on:
  push:
    branches:
      - development
env:
  NODE_VERSION: "10.x"
jobs:
  POST-test-case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%F_%H-%M-%S')"
      - name: curl
        run: |
          curl -o ../../test/security/sql-injection/test-sql-injection-users-${{steps.date.outputs.date}}.json -v -X POST -d "{\"firstName\": \"injection\", \"lastName\": \"You got hacked\",\"email\": \"'ups!!'); DELETE FROM users WHERE userId > 1020; -- \"}" https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users?      - name: read output
        id: taskId
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "../../test/security/sql-injection/test-sql-injection-users-${{steps.date.outputs.date}}.json"
          prop_path: "taskId"
      - run: echo ${{steps.taskId.outputs.prop}}
