name: UI Test /users

on:
  push:
    branches:
      - feature/task192-ReactUITest

env:
  NODE_VERSION: '14'
  UI_TESTS_PATH: './test/ui'

jobs:
  # Tentative title for the job
  ui-test-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
      
      - name: npm install, build, and test
        run: |
          pushd ${{ env.UI_TESTS_PATH }}
          npm install
          npm run test-users
          popd

