name: UI Test /users

on:
  push:
    branches:
      - feature/task192-ReactUITest

env:
  NODE_VERSION: '14'
  UI_TESTS_PATH: './test/ui'
  UI_RESULTS_USERS_FILE_PATH: './test/results/ui-test-results/ui-test-users-page-screenshot.png'
  UI_RESULTS_USERS_FILE_NAME: 'ui-test-users-page-screenshot.png'

jobs:
  # Tentative title for the job
  ui-test-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
      
      - name: npm install, build, and test
        run: |
          pushd ${{ env.UI_TESTS_PATH }}
          npm install
          npm run test-users
          popd
      
      - name: Upload to Azure storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload \
              --conection-string ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }} \
              --file ${{ env.UI_RESULTS_USERS_FILE_PATH }} \
              --container-name 'screenshots' \
              --name ${{ env.UI_RESULTS_USERS_FILE_NAME }}

